spring:
  application:
    name: CuentasBancariasCucumber
  datasource:
    url: jdbc:mysql://localhost:3306/cuentas_bancarias
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

